backend:
  name: git-gateway


collections:
  - name: "services"
    label: "Services"
    folder: "src/services"
    create: true
    slug: "{{ slug }}"
    fields:
      - {
        label: "Title",
        name: "title",
        widget: "string"
      }

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "assets/img"